tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/git"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Modern replacement for 'ls'
brew "exa"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven@3.2", link: true
# Move, copy, append, and link multiple files
brew "mmv"
# Port scanning utility for large networks
brew "nmap"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk@11", link: true
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Vault
brew "hashicorp/tap/vault", link: false
# Web browser
cask "firefox"
# Go (golang) IDE
cask "goland"
# Terminal built on web technologies
cask "hyper"
# Java IDE by JetBrains
cask "intellij-idea"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Word processor
cask "microsoft-word"
# Collaboration platform for API development
cask "postman"
# IDE for professional Python development
cask "pycharm"
# Music streaming service
cask "spotify"
# Video communication and virtual meeting platform
cask "zoom"
