#!/usr/bin/env zsh

# MIT License
#
# Copyright (c) 2021 Yasin Miran
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ======================================================================================
# Functions
# ======================================================================================

# This function writes all installed casks/formulae/images/taps
# into a `Brewfile` in the current directory.
#
# @arg -v install prints output from commands as they are run.
# check lists all missing dependencies.
#
# @arg -f dump overwrites an existing Brewfile. cleanup actually
# performs its cleanup operations.
#
# @arg --describe dump adds a description comment above each line,
# unless the dependency does not have a description.
function brew_dump() {
  echo "Dumping changes to Brewfile..." &&
    brew bundle dump -v --force --describe &&
    echo "Updated $HOMEBREW_BUNDLE_FILE."
}

# Clean my shit.
function brew_clean() {
  echo "Cleaning symbolic links..." &&
    brew cleanup
}

# Install all the dependencies using the available `Brewfile`.
# First it will tap necessary repos and install packages then casks.
function brew_bundle() {
  echo -e "Bundling your brew via Brewfile" &&
    brew bundle --verbose
}

# Install the given formulae and call brubf to add
# the newly installed to `Brewfile`.
function brew_install() {
  brew install "$1" || exit &&
    brew_dump
}

# ======================================================================================
# Exports
# ======================================================================================

# Currently, you can't do `brew bundle --no-quarantine` as an option.
# export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"
# https://github.com/Homebrew/homebrew-bundle/issues/474
export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"
export DOTFILES_BREW_DIR="$DOTFILES_DIR/brew"
export HOMEBREW_BUNDLE_FILE="$DOTFILES_BREW_DIR/Brewfile"
