#!/usr/bin/env bash

# This file contains the bootstrap logic for homebrew. This shouldn't be called
# everytime (although its fine). These commands, in this file intended
# to call from dotbot shell configuration when configuring a new machine.
#
# First source the brew related default configurations to the shell environment.
# We can ensure that zshrc variables are in the env because we source it after
# linking. See dotbot config for `source zsh/zshrc` shell command.

source "$DOTFILES_DIR/brew/defaults"

# Install homebrew via curl. If brew is already installed then just update
# the packages and exit.
# Documentation: https://docs.brew.sh/Installation
if command -v brew &>/dev/null; then
  echo "Hey $USER, homebrew is already installed :)"
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# By default when after a successful brew installation we will bundle the
# packages using the Brewfile.
brew_bundle && # Re-instate the packages, casks, and mas.
  brew_clean &&
  brew_dump # Update the Brewfile once again.
