#!/usr/bin/env zsh

# Generate SSH key in default location (~/.ssh/id_ed25519)
ssh-keygen -t ed25519 -C "wytm97@protonmail.com"

# Start the ssh-agent
eval "$(ssh-agent -s)"

# Create config file with necessary settings
if [[ "$(uname)" == "Darwin" ]]; then
  # macOS specific SSH config
  cat >~/.ssh/config <<EOF
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOF
elif [[ "$(uname)" == "Linux" ]]; then
  # Linux specific SSH config
  cat >~/.ssh/config <<EOF
Host *
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_ed25519
EOF
fi

# Add private key to ssh-agent
if [[ "$OS_TYPE" == "Darwin" ]]; then
  ssh-add -K ~/.ssh/id_ed25519
else
  ssh-add ~/.ssh/id_ed25519
fi

echo "Git setup is completed ✅"
echo "Please add the following public key to GitHub 🐙"
cat ~/.ssh/id_ed25519.pub
echo "After you add the key execute: 'ssh -T git@github.com' to see whether its working."
