# Tool for managing OCI containers and pods
brew "podman"
# Alternative to docker-compose using podman
brew "podman-compose"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Desktop password and login vault
cask "bitwarden"
# Web browser focusing on privacy
cask "duckduckgo"
# Go (golang) IDE
cask "goland"
# Open-source code editor
cask "visual-studio-code"
