#!/usr/bin/env zsh

# ======================================================================================
# Aliases
# ======================================================================================

alias dlistall="docker ps -a"
alias dstart="docker start"
alias dstop="docker stop"
