#!/usr/bin/env zsh

# ======================================================================================
# Aliases
# ======================================================================================

alias npmg="npm list -g --depth 0" # List all global packages
alias npmr="npm run"               # run quick
alias npmrs="npm run start"        # npm run start quick
alias next_dev="npm run dev:watch" # NextJS site dev

# ======================================================================================
# Functions
# ======================================================================================

# NextJS projects only.
function force_clean_packages() {
  rm -rf node_modules package-lock.json .next &&
    npm install
}

# This is a project specific function that I use mainly for
# cleaning up and starting a fresh instance.
function force_clean_and_build() {
  force_clean_packages &&
    npm run build &&
    npm run dev:watch
}

