#!/usr/bin/env zsh

# First do source the default aliases, exports, functions,
# and commands to this file to ensure all are loaded.
source "$DOTFILES_DIR/node/defaults"

if exists npm; then
  # Install global Node packages.
  echo "Installing your Node global packages."
  packages=(
    kill-port
  )
  for package in "${packages[@]}"; do
    npm install --global "$package"
  done
else
  echo "Node is not installed properly. Couldn't find 'npm'"
fi
