#!/usr/bin/env zsh

# MIT License
#
# Copyright (c) 2021 Yasin Miran
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ======================================================================================
# FUNCTIONS
# ======================================================================================

# Check the existence of a passed command but discard
# the outcome through redirection whether its successful
# or erroneous. The callee must use the exit code to
# determine whether its available or not.
#
# References:
# https://askubuntu.com/a/1005292
# https://tldp.org/LDP/abs/html/io-redirection.html
#
# Terminology:
# File descriptor 0 is the standard input (stdin). [Keyboard]
# File descriptor 1 is the standard output (stdout). [Display]
# File descriptor 2 is the standard error (stderr). [Display]
#
# Also be worth noting that the same semantics are often
# achieved with the idiom &>/dev/null
function exists() {
  command -v "$1" 1>/dev/null 2>&1
}
