#!/usr/bin/env zsh

source "$DOTFILES_DIR/snap/defaults"

# Main script starts here
if is_snap_installed; then
  echo "Snap is already installed. Skipping installation."
else
  echo "Snap is not installed. Installing Snap..."
  # Update apt repository
  echo "Updating apt repository..."
  sudo apt update
  # Install snapd (the Snap package manager)
  echo "Installing snapd..."
  sudo apt install snapd -y
  # Verify installation
  if is_snap_installed; then
    echo "Snap has been successfully installed."
    ask
  else
    echo "There was an issue installing Snap. Please check the logs above for any errors."
  fi
fi

# Now that snapd is ensured to be installed,
# proceed with installing snaps from the list
echo "Proceeding with installation of Snap packages from $SNAPLIST_FILE..."
install_snaps_from_list
